
USE clothestore;
CREATE TABLE PRODUCTS(
	productID INT AUTO_INCREMENT PRIMARY KEY,
	productName VARCHAR(255),
	categoryID INT,
	price DECIMAL(10,2),
	stock INT,
	status VARCHAR(100),
	img VARCHAR(255),
	DESCRIPTION VARCHAR(255)
	
);
CREATE TABLE CATEGORY(
	categoryID INT AUTO_INCREMENT PRIMARY KEY,
	categoryName VARCHAR(255)
);
CREATE TABLE ADDRESS(
	addressID  INT AUTO_INCREMENT PRIMARY KEY,
	address VARCHAR(255),
	district NVARCHAR(255),
	city NVARCHAR(255),
	country NVARCHAR(255),
	postalCode VARCHAR(100)
);
CREATE TABLE USERS(
	userID INT AUTO_INCREMENT PRIMARY KEY,
	firstName NVARCHAR(255),
	lastName NVARCHAR(255),
	email VARCHAR(255),
	addressID INT,
	verify BIT,
	username VARCHAR(255),
	password VARCHAR(255)
);

CREATE TABLE ORDERS(
	orderID INT AUTO_INCREMENT PRIMARY KEY,
	userID INT,
	orderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	status NVARCHAR(255)
);
CREATE TABLE ORDER_DETAILS(
    orderDetailID INT AUTO_INCREMENT PRIMARY KEY,
    orderID INT,
    productID INT,
    quantity INT,
    price DECIMAL(10,2),
    FOREIGN KEY (orderID) REFERENCES ORDERS(orderID),
    FOREIGN KEY (productID) REFERENCES PRODUCTS(productID)
);


ALTER TABLE USERS
ADD CONSTRAINT fk_USER_ADDRESS
FOREIGN KEY (addressID) REFERENCES ADDRESS(addressID);

ALTER TABLE PRODUCTS
ADD CONSTRAINT fk_PRODUCTS_CATEGORY
FOREIGN KEY (categoryID) REFERENCES CATEGORY(categoryID);

ALTER TABLE ORDERS ADD CONSTRAINT fk_ORDER_USER 
FOREIGN KEY (userID) REFERENCES USERS(userID);

